# Site
repository: danieltekour/danieltekour.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel Tekour
title: E-Bay Dropshipper, Student
email: tekour.daniel@seznam.cz
website: www.danieltekour.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  danieltekour
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: tekourdaniel
# flickr_username: jekyll
instagram_username: daniel_tekour
linkedin_username: daniel-tekour
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Daniel Tekour, I'am 20 years old and I have studied the high school SOŠ a SOU Kralupy nad Vltavou with IT. Now Iam learning english course in MAVO school for one school year.
  I have skills in fight sport Kick-Box thats I was make for 2 years.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/danieltekour
       
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DALTECOR Company
        link: www.danieltekour.com
        # link_text: www.danieltekour.com
        sub_title: Dropshipper
        caption: 2022


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  SOŠ a SOU Kralupy
        caption: 2018 - 2022
        sub_title: IT
        quote: >
          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
