# Site
repository: danieltekour/danieltekour.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel Tekour
title: E-Bay Dropshipper, Student
email: tekour.daniel@seznam.cz
website: www.danieltekour.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  danieltekour
facebook_username: tekourdaniel
instagram_username: daniel_tekour
linkedin_username: daniel-tekour-b1524a248

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
Hi, I’m Daniel Tekour, 20 years old student at MAVO language school. 
Apart from learning languages, in my free time I’m also doing kick-box, traveling to interesting places or working on my dropshipping business. 
Don’t worry to hit me up, I’m always open to anything.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My GitHub profile link:
        link: github.com/danieltekour
       
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DALTECOR Company
        link: www.danieltekour.com
        # link_text: www.danieltekour.com
        sub_title: Dropshipper
        caption: 2022


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  SOŠ a SOU Kralupy
        caption: 2018 - 2022
        sub_title: IT
        quote: >During my time at high school I learned mostly about how computer networks works,
        how to manage windows servers, Linux machines, basics of computer network theory, networking models and concepts etc.
          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
